---
  - name: "Restart {{schema_registry_service_name}} service"
    systemd: 
      daemon_reload: true
      name: "{{schema_registry_service_name}}"
      state: restarted

  - name: "Check if schema registry port {{schema_registry_server_port}} is up"
    wait_for:
      port: "{{schema_registry_server_port}}"
      connect_timeout: 3
      delay: 2
      timeout: 30
