---
  - name: "Restart {{ zookeeper_service_name }} service"
    systemd:
      daemon_reload: true
      name: "{{zookeeper_service_name}}"
      state: restarted

  - name: "Check if zookeeper port {{ zookeeper_server_port}} is up"
    wait_for:
      port: "{{zookeeper_server_port}}"
      connect_timeout: 5
      delay: 1
      timeout: 30
  
