- name: Deploy node_exporter and jmx_exporter
  hosts: all
  tasks:
  - name: Importing jmx prometheus role
    include_role:
      name: "{{ roleitem }}"
    loop:
    - node_exporter
    - prometheusjmx
    loop_control:
        loop_var: roleitem

- import_playbook: Restart_zookeeper.yml

- import_playbook: Restart_kafka_broker.yml

- import_playbook: Restart_schema_registry.yml
       
