---
# tasks file for prometheus

- name: Create Prometheus install  and config directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    mode: 0755
  loop:
  - "{{ jmxexporter_jar_path | dirname }}"
  - "{{ jmxexporter_config_path }}"

- name: Download Prometheus JMX Exporter Jar
  get_url:
    url: "{{ jmxexporter_jar_url }}"
#    dest: "{{ jmxexporter_jar_path }}"
    dest: '/tmp/'
#    force: "{{ jmxexporter_jar_url_force }}"
    mode: 0755
#    owner: "{{kafka_broker_user}}"
#    group: "{{kafka_broker_group}}"
  delegate_to: localhost
  register: prometheus_download_result
  until: prometheus_download_result is success
  retries: 5
  delay: 5

- name: Deploy jmx JAR on server
  copy:
    src: "/tmp/jmx_prometheus_javaagent-{{jmxexporter_version}}.jar"
    dest: "{{jmxexporter_jar_path}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"

- name: Deploy kafka_broker JMX Exporter Config File
  copy:
    src: "{{kafka_broker_jmxexporter_config_source_path}}"
    dest: "{{kafka_broker_jmxexporter_config_path}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  tags: 
    - configuration
    
- name: Create kafka_broker Service Override Directory
  file:
    path: "{{kafka_broker.systemd_override | dirname}}" 
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    state: directory
    mode: 0640

- name: Check if kafka_broker overrride.conf present or not 
  stat:
    path: "{{kafka_broker.systemd_override}}"
  register: brk_ovride

- name: Write kafka_broker Service Overrides
  template: 
    src: kafka_broker_override.conf.j2
    dest: "{{kafka_broker.systemd_override}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when: not brk_ovride.stat.exists 
  register: fileoverride

- name: Test if prometheus conf present
  shell: 'grep -c "prometheus" {{kafka_broker.systemd_override}} || true'
  register: promconfcheck_brk
  when: brk_ovride.stat.exists

- name: Add prometheus javagent config line in existing override.conf
  lineinfile:
    path: "{{kafka_broker.systemd_override}}"
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    backrefs: yes
    backup: yes
  loop:
  - { reg: '^(.*KAFKA_JMX_OPTS=.*)"$', line: '\1 -javaagent:{{jmxexporter_jar_path}}={{kafka_broker_jmxexporter_port}}:{{kafka_broker_jmxexporter_config_path}}"' }
  - { reg: '^(.*KAFKA_OPTS=.*)"$', line: '\1 -javaagent:{{jmxexporter_jar_path}}={{kafka_broker_jmxexporter_port}}:{{kafka_broker_jmxexporter_config_path}}"' }
  when: brk_ovride.stat.exists == true and promconfcheck_brk.stdout == "0"
  register: jmxbrkadd

- name: Test if prometheus conf present
  shell: 'grep -c "prometheus" {{kafka_broker.systemd_override}} || true'
  register: promconfcheck_brk1
  when: brk_ovride.stat.exists

- name: Add prometheus javagent config line in existing override.conf
  lineinfile:
    path: "{{kafka_broker.systemd_override}}"
    line: 'Environment="KAFKA_JMX_OPTS=-javaagent:{{jmxexporter_jar_path}}={{kafka_broker_jmxexporter_port}}:{{kafka_broker_jmxexporter_config_path}}"'
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    backup: yes
  when: 
  - brk_ovride.stat.exists
  - promconfcheck_brk1.stdout == "0"
  register: jmxbrkadd1

- name: Systemd reload
  systemd:
    daemon_reload: true 

- name: Get broker id 
  shell: |
    export brkid=$(ps -ef | grep -i server.properties | grep -v grep  | awk '{print $NF}')
    grep broker.id ${brkid} | awk -F'=' '{print $2}'
  register: brokerid

- name: Debug brokerid
  debug: var=brokerid

- name: Get controller id 
  shell: "echo dump | nc {{groups['zookeeper'][0]}} {{ hostvars[groups['zookeeper'][0]].zk_port}} | grep -A 2 -i controller | grep -i brokers | awk -F '/' '{print $NF}'"
  register: controllerid 
  delegate_to: localhost

- name: Debug controller id
  debug: var=controllerid

- name: Restart follower broker
  throttle: 1
  any_errors_fatal: true
  shell: |
     systemctl restart {{kafka_broker_service_name}} 
     timeout -k 3 1m sh -c 'until nc -zv localhost {{kafka_broker_server_port}}; do sleep 1; done'
     sleep 30s
  when: 
    - brokerid.stdout_lines[0] | int != controllerid.stdout_lines[0] | int
    - jmxbrkadd.changed or jmxbrkadd1.changed or fileoverride.changed  
    - kafka_broker_restart|bool

- name: Restart controller broker
  throttle: 1
  any_errors_fatal: true
  shell: |
     systemctl restart {{kafka_broker_service_name}}  
     timeout -k 3 1m sh -c 'until nc -zv localhost {{kafka_broker_server_port}}; do sleep 1; done'
     sleep 30s
  when: 
    - brokerid.stdout_lines[0] | int == controllerid.stdout_lines[0] | int
    - jmxbrkadd.changed or jmxbrkadd1.changed or fileoverride.changed  
    - kafka_broker_restart|bool
